apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se-debian-repos
  namespace: ec-eg
spec:
  hosts:
    - deb.debian.org
    - security.debian.org
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS
